spring.application.name=parkingLot_Spring

spring.datasource.url=jdbc:mysql://localhost:3306/parkinglot
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true

parking.pricing.policy = TIME_BASED
parking.pricing.description = FEE WILL CALCULATE BASED ON TIME BASED.
parking.device.waiting-time=1m
